production: &default
  adapter: postgresql
  encoding: unicode
  database: postgres
  pool: 5
  username: postgres
  password: postgrespostgres
  host: db

test:
  <<: *default
  database: myapp_test
